services:
  puertocho-assistant-whisper:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: whisper-api
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - env
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"
    volumes:
      - ./debug_audio:/app/debug_audio
      - ./audio:/app/audio
